const clubList: { [index: string]: string} = {
  "AIA": "Platinum AIA Capital Center",
  "LMP": "Platinum Landmark Plaza",
  "QHL": "Platinum Q House Lumpini",
  "SSQ": "Platinum Sathorn Square",
  "SPG": "Platinum Siam Paragon",
  "CTW": "Zone CentralWorld",
  "CHY": "CentralFestival Hatyai",
  "CBN": "Centralplaza Bangna",
  "CHW": "Centralplaza Chaengwattana",
  "CBR": "CentralPlaza Chonburi",
  "RM9": "CentralPlaza Grand Rama 9",
  "CKK": "CentralPlaza Khonkaen",
  "CPK": "CentralPlaza Pinklao",
  "RM2": "CentralPlaza Rama 2",
  "RM3": "CentralPlaza Rama 3",
  "RTB": "CentralPlaza Rattanathibet",
  "CUD": "CentralPlaza Udonthani",
  "P39": "Club 39",
  "FPK": "Future Park Rangsit",
  "PKS": "Home Pro Petchkasem",
  "MBN": "Mega Bangna",
  "SCS": "Seacon Square",
  "T21": "Terminal 21",
  "CRD": "The Crystal Ramindra",
  "CRP": "The Crystal SB Ratchapruek",
  "BKP": "The Mall Bangkapi",
  "BKE": "The Mall Bangkhae",
  "KRT": "The Mall Korat",
  "NWW": "The Mall Ngamwongwan",
  "MTP": "The Mall Thapra",
  "PRM": "The Promenade",
};

export default clubList;